name: test
on: [ push ]
jobs:

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
        id: go

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: go test -v ./...
        env:
          USE_EXISTING_CLUSTER: true
